Feature/cuenta bancaria
udistrital/contabilidad_cliente pull request #129
Opened 2021-10-31 03:57 UTC by Jeisson005

Antes de realizar el pull, se debe realizar el pull a las dependencias.
Todo se probó de forma local con las configuraciones adecuadas en las ramas correspondientes a esos pr

Depende de PRs:
udistrital/cuentas_contables_crud#56
udistrital/tesoreria_mid/pull/19

Close udistrital/contabilidad_cliente#92
Close udistrital/financiera_documentacion#363

2021-10-31 05:22 UTC, AlexFBP requested changes
En general bien.
- Hay código duplicado y/o que se podría extender, revisar
- Variables de entorno solo funcionarían bajo VPN, revisar

2021-10-31 05:22 UTC, AlexFBP commented on src/app/@core/helpers/giros/girosHelper.ts
> +    public getCuentasBancarias(parameters?: { id?: any, query?: any, fields?: string[], sortby?: string[], order?: string[], limit?: number, offset?: number }) {
Se observa que `{ id?: any, query?: any, fields?: string[], sortby?: string[], order?: string[], limit?: number, offset?: number }` se repite en varias partes.
Guardar esta estructura como un nuevo modelo de datos, por ejemplo, algo como `BeegoQueryParams`:
```typescript
interface BeegoQueryParams {
  id?: string; // evitar el any
  query?: string; // evitar el any
  fields?: string[];
  sortby?: string[];
  order?: string[];
  limit?: number;
  offset?: number;
}
...
export {..., BeegoQueryParams};
```

De tal manera que el `getCuentasBancarias` (y dondesea que se use esta misma estructura) se pueda reescribir como
```typescript
import {BeegoQueryParams} from '...';
...
public getCuentasBancarias(parameters?: BeegoQueryParams){...}
```

(Si no funciona con `interface` usar simplemente `class`)

2021-10-31 05:22 UTC, AlexFBP commented on src/app/@core/helpers/terceros/tercerosHelper.ts
> +    public getTerceros(parameters?: { id?: any, query?: any, fields?: string[], sortby?: string[], order?: string[], limit?: number, offset?: number }) {
Ver lo comentado en src/app/@core/helpers/giros/girosHelper.ts

2021-10-31 05:22 UTC, AlexFBP commented on src/app/@core/helpers/terceros/tercerosHelper.ts
> +    public getTerceroTipoTercero(parameters?: { id?: any, query?: any, fields?: string[], sortby?: string[], order?: string[], limit?: number, offset?: number }) {
Ver lo comentado en src/app/@core/helpers/giros/girosHelper.ts

2021-10-31 05:22 UTC, AlexFBP commented on src/app/@core/helpers/tesoreria/tesoreriaHelper.ts
> +    public getCuentasBancarias(parameters?: { id?: any, limit?: number, offset?: number }) {
Posiblemente se pueda hacer algo similar a lo comentado en src/app/@core/helpers/giros/girosHelper.ts

2021-10-31 05:22 UTC, AlexFBP commented on src/app/@core/managers/requestManager.ts
> +  getv2(endpoint: string, parameters?: { id?: any, query?: any, fields?: string[], sortby?: string[], order?: string[], limit?: number, offset?: number }) {
Ver lo comentado en src/app/@core/helpers/giros/girosHelper.ts respecto a `parameters`

2021-10-31 05:22 UTC, AlexFBP commented on src/environments/environment.ts
> +  TESORERIA_MID_SERVICE: 'http://pruebasapi2.intranetoas.udistrital.edu.co:8214/v1/',
- Esto solo funcionaría bajo VPN, no se encuentra desplegado?
- Ajustar no solo acá sino en el .test.ts y en el .prod.ts

2021-10-31 05:22 UTC, AlexFBP commented on src/environments/environment.test.ts
> +  TESORERIA_MID_SERVICE: 'http://pruebasapi2.intranetoas.udistrital.edu.co:8214/v1/',
Revisar lo comentado en src/environments/environment.ts

2022-02-05 23:48 UTC, closed without merging

2022-02-05 23:49 UTC, salcedogeiner commented
se cierra PR ya que se continua desarrollo en otra rama