Feature/arbol contable refactor
udistrital/contabilidad_cliente pull request #134
Opened 2022-01-02 02:10 UTC by salcedogeiner

2022-01-02 05:44 UTC, AlexFBP requested changes
En general, bien. Si bien se dejaron varios comentarios, la mayoría quedaron como _suggested changes_ que se pueden seleccionar y aplicar desde la interfaz web. La mayoría son respecto a evitar código comentado

2022-01-02 05:44 UTC, AlexFBP commented on src/app/@theme/components/reactive-form/reactive-control/reactive-control.component.ts
> +    // return formControl;
Si no se necesita, eliminar esto
```suggestion
```
Alternativamente, dejar comentado (también) en código, por qué se dejó comentado y/o cómo proceder

2022-01-02 05:44 UTC, AlexFBP commented on src/app/@theme/components/reactive-form/reactive-control/reactive-control.component.ts
> +
Evitar dejar código comentado
```suggestion
```

2022-01-02 05:44 UTC, AlexFBP commented on src/app/@theme/components/reactive-form/reactive-control/reactive-control.component.ts
> +      // this.control.setValue(value);
Evitar dejar código comentado
```suggestion
      this.control.setValidators(this.data.validators);
```
Alternativamente, dejar comentado también (en código) por qué se dejó comentado y/o cómo proceder al respecto

2022-01-02 05:44 UTC, AlexFBP commented on src/app/@theme/components/reactive-form/reactive-control/reactive-control.component.ts
> +    // const formControl = new FormControl(item.defaultValue, item.validators);
Evitar código comentado
```suggestion
```

2022-01-02 05:44 UTC, AlexFBP commented on src/app/@theme/styles/themes.scss
> +// ), kronos-propuesta, default);
Entiendo que esto seguramente venga de algún paso faltante en [la migración de Nebular 3 a 4](https://akveo.github.io/nebular/docs/migration/350400-migration#350--400-nebular-migration). 

Considerar las siguientes alternativas:
- Ajustar de acuerdo a los pasos de la migración
- Eliminar
- Dejar como deuda técnica para otro Issue

Cualquiera de las tres es válida, podría haber otra mejor. Sea cual sea el caso, indicar por acá por cuál se optaría

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/arbol-contable/arbol-contable.component.ts
> +        !!node.children && !!node.children.length ? node.children : [],
Desambiguar agregando grupos de parentesis cuando haya anidación de ternas o para facilitar la lectura y no depender de la jerarquía de operadores...
```typescript
A && B ? C : D
// podría significar, entre otras alternativas:
(A && B) ? C : D
A && (B ? C : D)
```

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/arbol-cuentas-contables.component.html
> +</div>
(En general) Dejar vacía, sin espacios ni nada, la última línea de cualquier archivo de texto plano
```suggestion
</div>

```

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/arbol-cuentas-contables.component.scss
> +:host ::ng-deep .mat-tab-label-content {
Si se puede [evitar `::ng-deep`](https://dev.to/jwp/angular-10-ng-deep-and-host-pseudo-classes-1kbg), mejor, mas no es imprescindible

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +
Eliminar
```suggestion
```
Alternativamente, dejar comentado también el por qué debería dejarse comentado y/o cómo proceder

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +    </nb-card>
Dejar vacía la última línea de cualquier archivo de texto plano
```suggestion
    </nb-card>

```

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.ts
> +      // this.acountService.updateNode(this.form.value.Codigo, this.form.value);
Eliminar
```suggestion
```
Alternativamente, dejar comentado también (en código) por qué debería dejarse comentado y/o cómo proceder

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/selector-contable/selector-contable.component.html
> +</nb-card>
```suggestion
</nb-card>

```

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/selector-contable/selector-contable.component.ts
> +      // codigos.pop();
Eliminar...
```suggestion
```
... o dejar comentado también (en código) por qué se dejó comentado y/o cómo proceder a futuro al respecto

2022-01-02 05:44 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/selector-contable/selector-contable.component.ts
> +        parent.get(item.child) && typeof parent.get(item.key).value !== 'object' ? parent.get(item.child).setValue('') : null;
Si no se requiere el valor retornado por una terna, optar por una alternativa explícita
```suggestion
        if (parent.get(item.child) && typeof parent.get(item.key).value !== 'object') {
          parent.get(item.child).setValue('');
        }
```
**NOTA:** Revisar si este _suggested change_ tal cual como se dejó, funcionaría o si habría que ajustarlo o si no aplica...

2022-01-03 00:14 UTC, salcedogeiner commented on src/app/@theme/components/reactive-form/reactive-control/reactive-control.component.ts
> +        item.valueChanges ? item.valueChanges(this.control.parent) : null;
No siempre es necesario que el uso de la terna se amarre a la asignacion de un valor. Puede usarse para ejecucion de sentencias abreviando el codigo sin dificultad la legibilidad.
Depende el punto de vista ...

2022-01-03 03:25 UTC, AlexFBP approved these changes
Aprobado con comentarios pendientes

2022-01-03 03:25 UTC, merged