Feature/bancos cuentas
udistrital/contabilidad_cliente pull request #145
Opened 2022-02-05 23:59 UTC by salcedogeiner

https://github.com/udistrital/financiera_documentacion/issues/363

2022-02-06 04:03 UTC, AlexFBP requested changes
En general bien. Principalmente revisar lo comentado en los siguientes archivos
- `src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html`
- `src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.ts`

De resto, son comentarios de i18n: Cualquier texto destinado a aparecer en la interfaz de usuario, debería tomarse de i18n

2022-02-06 04:03 UTC, AlexFBP commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.ts
> +  }
Esto se ve bueno, hay posibilidad de dejarlo en un archivo .ts de utilidades aparte?
Digamos, creando/editando alguno de los archivos dentro de `src/app/@core` o en `src/app/shared`
Considerarlo, cosa que si mas adelante se necesita, se pueda reaprovechar...

2022-02-09 01:47 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +	[editable]="cuenta ? false : true"
ajustado

2022-02-09 01:47 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							placeholder="Codigo"
ajustado

2022-02-09 01:47 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-hint><strong>Ingrese el código consecutivo</strong> </mat-hint>
ajustado

2022-02-09 01:48 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Moneda*</mat-label>
ajustado

2022-02-09 01:48 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Codigo*</mat-label>
ajustado

2022-02-09 01:48 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +								form.controls["Codigo"].errors.msg || "ingrese un dato valido"
ajustado

2022-02-09 01:48 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +								form.controls["CuentaBancariaID"].errors.msg || "ingrese un dato valido"
ajustado

2022-02-09 01:48 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +								form.controls["MonedaID"].errors.msg || "ingrese un dato valido"
ajustado

2022-02-09 01:54 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +			<button mat-flat-button color="primary" type="submit">Confirmar</button>
ajustado

2022-02-09 01:54 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.ts
> +  }
ajustado

2022-02-09 01:55 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							>Disponible</mat-slide-toggle
ajustado

2022-02-09 01:55 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Nombre*</mat-label>
ajustado

2022-02-09 01:55 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							placeholder="Nombre"
ajustado

2022-02-09 01:55 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +								form.controls["Nombre"].errors.msg || "ingrese un dato valido"
ajustado

2022-02-09 01:55 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							><strong>Ingrese el nombre de la cuenta</strong>
ajustado

2022-02-09 01:55 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Naturaleza*</mat-label>
ajustado

2022-02-09 01:56 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +									"ingrese un dato valido"
ajustado

2022-02-09 01:56 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Tipo Cuenta*</mat-label>
ajustado

2022-02-09 01:56 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +									"ingrese un dato valido"
ajustado

2022-02-09 01:56 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Detalle*</mat-label>
ajustado

2022-02-09 01:57 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +									"ingrese un dato valido"
ajustado

2022-02-09 01:57 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							>Requiere Tercero</mat-slide-toggle
ajustado

2022-02-09 01:57 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							>Ajustable</mat-slide-toggle
ajustado

2022-02-09 01:57 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							>NMNC</mat-slide-toggle
ajustado

2022-02-09 01:57 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Centro De costos</mat-label>
ajustado

2022-02-09 01:58 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +									"ingrese un dato valido"
ajustado

2022-02-09 01:58 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +						<mat-label>Cuenta Bancaria</mat-label>
ajustado

2022-02-09 01:58 UTC, salcedogeiner commented on src/app/pages/arbol-cuentas-contables/cuenta-contable/cuenta-contable.component.html
> +							placeholder="Banco"
ajustado

2022-02-09 20:10 UTC, AlexFBP approved these changes

2022-02-09 20:10 UTC, merged